#!/usr/bin/env python

import click

import sys

from core.lexer import Lexer
from core.parser import Parser


lexer = Lexer()
parser = Parser()


@click.group()
def cli():
    pass

@cli.command()
@click.option(
    '--program-file',
    help='program file used as input',
    type=click.File('r'),
    default=sys.stdin)
def lex(program_file):
    """Perform Lexical Analysis"""
    with program_file:
        program = program_file.read()
        for token in lexer(program):
            parts = [str(token.line), str(token.offset), token.label]
            if token.value is not None:
                parts.append(token.value)
            print('\t'.join(parts))


if __name__ == '__main__':
    cli()
